### ISSUE TITLE
Getting errors only on shopaholic plugins

### ISSUE THREAD

**Issue by nunohsilva** [oc-shopaholic/oc-orders-shopaholic-plugin#82]
Hi, I'm kinda new on this...
I'm using October for about 2 months now... I'm trying to use and check code from components of shopaholic or toolsbox and I'm getting this error.
I searched for help and I found that the problem could be a capital letter in a directory inside components folder, but I found nothing.
Error:
"Call to a member function getContent() on null" on line 386 of /home/nunosil2/public_html/october/modules/cms/controllers/Index.php

Help? :/

**Comment by kharanenka** [comment]
Hi! Components don't have templates, because each project has its own unique design and html structure. Logic of blocks may be similar, but with few differences. Therefore, so that developers don't have to freeze plugins, fitting logic to project, we provide flexible classes for rendering data in template.

You can find more information about plugins in new [docs](http://shopaholic.one/docs) (beta)
